services:
 zipkin:
  image: openzipkin/zipkin
  mem_limit: 700m
  ports:
   - "9411:9411"
  networks:
   - rdgpcampos-network

 configserver:
  image: rdgpcampos/config:latest
  mem_limit: 700m
  ports:
   - "8070:8070"
  networks:
   - rdgpcampos-network
  depends_on:
   - zipkin
  deploy:
   restart_policy:
    condition: on-failure
    delay: 5s
    max_attempts: 3
    window: 120s
  environment:
   MANAGEMENT.ZIPKIN.TRACING.ENDPOINT:  http://zipkin:9411/api/v2/spans

 servicebalancer:
  image: rdgpcampos/servicebalancer:latest
  mem_limit: 700m
  ports:
   - "8071:8071"
  networks:
   - rdgpcampos-network
  depends_on:
   - configserver
  deploy:
   restart_policy:
    condition: on-failure
    delay: 5s
    max_attempts: 3
    window: 120s
  environment:
   SPRING_PROFILES_ACTIVE: default
   SPRING_CONFIG_IMPORT: configserver:http://configserver:8070/
   MANAGEMENT.ZIPKIN.TRACING.ENDPOINT:  http://zipkin:9411/api/v2/spans

 bankaccounts:
  image: rdgpcampos/bankaccounts:latest
  mem_limit: 700m
  ports:
   - "8080:8080"
  networks:
   - rdgpcampos-network
  depends_on:
   - configserver
   - servicebalancer
  deploy:
   restart_policy:
    condition: on-failure
    delay: 5s
    max_attempts: 3
    window: 120s
  environment:
   SPRING_PROFILES_ACTIVE: default
   SPRING_CONFIG_IMPORT: configserver:http://configserver:8070/
   MANAGEMENT.ZIPKIN.TRACING.ENDPOINT:  http://zipkin:9411/api/v2/spans
   EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://servicebalancer:8071/eureka/

 loans:
  image: rdgpcampos/loan:latest
  mem_limit: 700m
  ports:
   - "8090:8090"
  networks:
   - rdgpcampos-network
  depends_on:
   - configserver
   - servicebalancer
  deploy:
   restart_policy:
    condition: on-failure
    delay: 5s
    max_attempts: 3
    window: 120s
  environment:
   SPRING_PROFILES_ACTIVE: default
   SPRING_CONFIG_IMPORT: configserver:http://configserver:8070/
   EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://servicebalancer:8071/eureka/
   MANAGEMENT.ZIPKIN.TRACING.ENDPOINT:  http://zipkin:9411/api/v2/spans

 cards:
  image: rdgpcampos/cards:latest
  mem_limit: 700m
  ports:
   - "9000:9000"
  networks:
   - rdgpcampos-network
  depends_on:
   - configserver
   - servicebalancer
  deploy:
   restart_policy:
    condition: on-failure
    delay: 5s
    max_attempts: 3
    window: 120s
  environment:
   SPRING_PROFILES_ACTIVE: default
   SPRING_CONFIG_IMPORT: configserver:http://configserver:8070/
   EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://servicebalancer:8071/eureka/
   MANAGEMENT.ZIPKIN.TRACING.ENDPOINT:  http://zipkin:9411/api/v2/spans

 gatewayserver:
  image: rdgpcampos/gateway:latest
  mem_limit: 700m
  ports:
   - "8072:8072"
  networks:
   - rdgpcampos-network
  depends_on:
   - configserver
   - servicebalancer
   - cards
   - loans
   - bankaccounts
  deploy:
   restart_policy:
    condition: on-failure
    delay: 45s
    max_attempts: 3
    window: 120s
  environment:
   SPRING_PROFILES_ACTIVE: default
   SPRING_CONFIG_IMPORT: configserver:http://configserver:8070/
   EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://servicebalancer:8071/eureka/
   MANAGEMENT.ZIPKIN.TRACING.ENDPOINT:  http://zipkin:9411/api/v2/spans

networks:
 rdgpcampos-network:
